// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghysnghgmsnhqxwltqgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoeXNuZ2hnbXNuaHF4d2x0cWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzgwNjUsImV4cCI6MjA2NzAxNDA2NX0.-Zm5DQcxeoQFAYN1LyiyWPpof42nZMxs-yL1N_9R2vU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});